apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    name: app1
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      name: app1
      tier: frontend
  template:
    metadata:
      labels:
        name: app1
        tier: frontend
    spec:
      containers:
      - name: app1
        image: shirisha02/app1:v1
---
apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  selector:
    name: app1
    tier: frontend
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80
    targetPort: 80        